apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tik5eowyr-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tik5eowyr-dotnet-basic-gitops